### ISSUE TITLE
Initial fixes; more representative graphs

### ISSUE THREAD

**Issue by Velythyl** [Velythyl/gym-duckietown#1]
# Initial fixes: 
the model's predictions were in tensor form. This corrupted the env once the mixing started using the model: the self.cur_pos became an np.array of 1d, 1-element tensor.

# Graphs: 
as-is, the tensorboard calls plotted the loss on each epoch, and also all the epoch losses on one graph. We'd instead like to have one single big curve for each run, showing how the loss evolves per episode. This will allow us to compare the different curves, and thus optimise the HPs better.

Simply plotting the losses doesn't work, though. It produces incomparable graphs: as time goes on, we collect more and more data samples, meaning the running loss of the last epoch of each episode it strictly bigger, simply because it acts on more observations and actions. This leads to the appearance that the loss is increasing over time. This is an illusion: it is the dataset that increases over time.

![image](https://user-images.githubusercontent.com/31974070/83979210-a0109680-a8da-11ea-863b-b9dcecc56f21.png)

We can convince ourselves of this by taking the mean of the losses w.r.t. to the size of the dataset. With that trick, we find the familiar curves normally associated with loss curves.

![image](https://user-images.githubusercontent.com/31974070/83979260-0f868600-a8db-11ea-80df-65a57fa746a6.png)

But that's also kind of bad: the numbers are so small that we're bound to have floating point errors. Instead, I planned on using the number of batches per dataset instead of the size of the dataset in the mean. But that would also be bad, as it would lose meaning if we change the batch size. So we're going to use a magic number instead, just so it doesn't vary with the HPs.

![image](https://user-images.githubusercontent.com/31974070/83980009-44e1a280-a8e0-11ea-8366-e6435667958c.png)

The magic number can be editted.

**Comment by bhairavmehta95** [comment]
If I'm not mistaken, you won't usually see floating point errors at this scale. But it's good to think about these things!

**Comment by Velythyl** [comment]
I felt like the curve was too smooth, but now that you mention it 2e-4 does seem a bit big for errors.

Do you think a normal mean is better instead of using a "batched mean"? I can change it for future people using this repo (but since training takes a while, I'll have to keep using the batched mean until I find a good HP set to have comparable graphs)

**Comment by bhairavmehta95** [comment]
Nope, batched mean is fine. 

We'll talk about the (un)importance of loss in control+learning settings on Thursday, so for now, this is good!
